buffy:
  env:
    bot_github_user: <%= ENV['PYOSBOT_GH_USER'] %>
    gh_access_token: <%= ENV['PYOSBOT_GH_ACCESS_TOKEN'] %>
    gh_secret_token: <%= ENV['PYOSBOT_GH_SECRET_TOKEN'] %>
  teams:
    editors: 6762239
  responders:
    help:
    hello:
      	hidden: true
    thanks:
      hidden: true
